#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -u

# Loads the generic functions usually used in the script
source _common
# Source app helpers
source /usr/share/yunohost/helpers

# Get multi-instances specific variables
app=$YNH_APP_INSTANCE_NAME

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)

# Stop telegram.chatbot service
if [ -e "/etc/systemd/system/${app}.service" ]; then
	echo "Delete systemd script"
	sudo service $app stop
	sudo rm "/etc/systemd/system/${app}.service"
	sudo systemctl disable $app.service
fi

# Remove monitoring service Yunohost.
if sudo yunohost service status | grep -q $app
then
	echo "Remove ${app} service"
	sudo yunohost service remove $app
fi

ynh_secure_remove "/opt/${app}"
ynh_secure_remove "/var/log/${app}"

# Remove user
ynh_system_user_delete $app

# Delete nginx config
ynh_remove_nginx_config

# Delete logrotate
ynh_remove_logrotate

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload


echo -e "\e[0m"	# Restore normal color